//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ComplaintManagementSystem.ITStaff
{
    public partial class ITStaffDashboard
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.GridView gvMyComplaints;
        protected global::System.Web.UI.WebControls.Button btnLogout;
    }
}
