//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Register
{

    protected global::System.Web.UI.HtmlControls.HtmlForm form1;

    protected global::System.Web.UI.WebControls.TextBox txtUsername;

    protected global::System.Web.UI.WebControls.TextBox txtEmail;

    protected global::System.Web.UI.WebControls.TextBox txtPassword;

    protected global::System.Web.UI.WebControls.DropDownList ddlRole;

    protected global::System.Web.UI.WebControls.Button btnRegister;

    protected global::System.Web.UI.WebControls.Label lblMessage;
}
