//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintManagementSystem.Admin
{
    public partial class AdminDashboard
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// gvComplaints control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvComplaints;

        /// <summary>
        /// btnLogout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLogout;
    }
}
